### ISSUE TITLE
No response from instanceId xxx

### ISSUE THREAD

**Issue by guilter** [MangoAutomation/BACnet4J#106]
I am getting the exception from some bacnet remote devices.
`com.serotonin.bacnet4j.exception.BACnetTimeoutException: No response from instanceId 1213
	at com.serotonin.bacnet4j.util.RemoteDeviceFinder$DeviceFutureImpl.get(RemoteDeviceFinder.java:183) ~[bacnet4j-6.0.0.jar!/:?]
	at com.serotonin.bacnet4j.LocalDevice$2.get(LocalDevice.java:727) ~[bacnet4j-6.0.0.jar!/:?]`

Another note is that most of these I-AM packets report Maximum APDU Length Accepted of 480.

After observing, I found that when the BACnet device's max-apdu-length-accepted property value is not equal to 1476, this exception occurs. However, when the value is set to 1476, it works normally. I'm unsure how to resolve this issue and seek assistance.

**Comment by Thisora** [comment]
I'm occuring the same exception after i recieve a message "I-Have-Request"

WARN com.serotonin.bacnet4j.service.unconfirmed.IHaveRequest -- Error while discovering extended device information
com.serotonin.bacnet4j.exception.BACnetTimeoutException: No response from instanceId <a-device-id>
	at com.serotonin.bacnet4j.util.RemoteDeviceFinder$DeviceFutureImpl.get(RemoteDeviceFinder.java:183)
	at com.serotonin.bacnet4j.LocalDevice.getRemoteDeviceBlocking(LocalDevice.java:816)
	at com.serotonin.bacnet4j.LocalDevice.getRemoteDeviceBlocking(LocalDevice.java:759)
	at com.serotonin.bacnet4j.service.unconfirmed.IHaveRequest.lambda$handle$0(IHaveRequest.java:79)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
