### ISSUE TITLE
Error while reading object list on remote device when the response is segmented

### ISSUE THREAD

**Issue by envas** [MangoAutomation/BACnet4J#80]
**Describe the bug**
There is a terrible bug in the Bacnet4J library during the segmented **response from remote device to ReadProperty object-list**. From a certain number of objects the server returns a segmented response. Bacnet4J for some reason misses the first segment of the response and therefore repeats the request. This leads to an error. 

**To Reproduce**

You can use Mango (IMO any release) and try to discover objects on a device with large number of object instances. In my case the problem was on a device with 750 data points, probably smaller number of instances generates the issue as well.

**Expected behavior**
Device responses the with the list of objects.

**Screenshots**
Yabe
<img width="1246" alt="Yabe" src="https://user-images.githubusercontent.com/25388570/224549360-88988c8b-30ef-4ae2-8d42-68c21a26dd56.png">

Bacnet4J
![Bacnet4J](https://user-images.githubusercontent.com/25388570/224549379-67197cd5-85ba-45c3-92a7-80991fa931da.png)

**Mango Version (please complete the following information):**
 - all Mango versions because the issue is in the Bacnet4J library

**Minimal code example to reproduce**
I was able to repeat the issue in my code:

```
 LocalDevice            localDevice  = bacnet.getLocalDevice();
        DeviceObject           deviceObject = bacnet.getDeviceObject();
        RemoteDeviceDiscoverer discoverer   = new RemoteDeviceDiscoverer(localDevice);

        // remote discovery callback
        ReadListener lsnr = (progress, deviceId, objectIdentifier, propertyIdentifier, pin, value) -> {
              Logger.info(" callback: device= %s oid=%s value=%s", deviceId, objectIdentifier.toString(),value);
              return true;
        };

        discoverer.start();
        ThreadUtils.sleep(5000);

        List<RemoteDevice> devices = discoverer.getRemoteDevices();

        for (RemoteDevice rd : devices) {

            DiscoveryUtils.getExtendedDeviceInformation(localDevice, rd);
            BLogger.info(rd.toExtendedString());

            if (rd.getInstanceNumber() == 24) {. // my device with > 750 data points

                try {

                    SequenceOf<ObjectIdentifier> oids = RequestUtils.getObjectList(localDevice, rd, lsnr);
                    Logger.info("successfully retrieved object list [total=%s objects]", String.valueOf(oids.size()));

                } catch (BACnetException e) {

                    Logger.error("error reading object list [errmsg=%s cause=%s]", e.getLocalizedMessage(), e.getCause());
                    e.printStackTrace();
                }
            }
        }

        discoverer.stop();
```
Eror tracking:

```
2023-03-12 14:06:00,062 [main           ] RemoteDevice(instanceNumber=24, address=Address [networkNumber=0, macAddress=[c0,a8,0,f4,ba,c0]], maxAPDULengthAccepted=1476, segmentationSupported=segmented-both, vendorId=865, vendorName=null, name=CBOX, servicesSupported=ServicesSupported[UnconfirmedCovNotification=true, UnconfirmedEventNotification=true, UnconfirmedPrivateTransfer=true, UnconfirmedCovNotificationMultiple=true, ConfirmedCovNotification=true, ConfirmedEventNotification=true, DeviceCommunicationControl=true, ConfirmedPrivateTransfer=true, SubscribeCovPropertyMultiple=true, ConfirmedCovNotificationMultiple=true, WhoHas=true, WhoIs=true, IAm=true, IHave=true, VtOpen=false, VtData=false, UnconfirmedTextMessage=true, TimeSynchronization=true, UtcTimeSynchronization=true, WriteGroup=false, AcknowledgeAlarm=true, GetAlarmSummary=true, GetEnrollmentSummary=true, SubscribeCov=true, AtomicReadFile=true, AtomicWriteFile=true, AddListElement=true, RemoveListElement=true, CreateObject=true, DeleteObject=true, ReadProperty=true, ReadPropertyMultiple=true, WriteProperty=true, WritePropertyMultiple=true, ConfirmedTextMessage=true, ReinitializeDevice=true, VtClose=false, ReadRange=true, LifeSafetyOperation=true, SubscribeCovProperty=true, GetEventInformation=true])
2023-03-12 14:06:06,079 [main           ] error reading object list [errmsg=ErrorAPDU(errorClass=services, errorCode=operational-problem,errorClass=services, errorCode=operational-problem) cause=null]
com.serotonin.bacnet4j.exception.ErrorAPDUException: ErrorAPDU(errorClass=services, errorCode=operational-problem,errorClass=services, errorCode=operational-problem)
	at com.serotonin.bacnet4j.transport.ServiceFutureImpl.result(ServiceFutureImpl.java:83)
	at com.serotonin.bacnet4j.transport.ServiceFutureImpl.get(ServiceFutureImpl.java:64)
	at com.serotonin.bacnet4j.util.RequestUtils.sendReadPropertyAllowNull(RequestUtils.java:175)
	at com.serotonin.bacnet4j.util.RequestUtils.getObjectList(RequestUtils.java:162)
	at com.neopsis.bacnet.RemoteDiscoveryTest.discover(RemoteDiscoveryTest.java:89)
```

**Comment by envas** [comment]
Closing, a firewall issue, sorry.

**Comment by envas** [comment]
My mistake, it was a firewall issue.
